version: '3'

services:
  mongo:
    image: mongo:3
    volumes:
      - mongo-data:/data/db
    expose:
      - "27017"

  app:
    image: jo12bar/message-app-2:0.0.1
    ports:
      - "8000:80"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo/messageApp2

volumes:
  mongo-data:
